###
#offers
##get offers
GET http://localhost:9000/offers HTTP/1.1

###
##get offer by Id
GET http://localhost:9000/offers/634527199c42583bf5b1f0a4 HTTP/1.1

###
## create offer
POST http://localhost:9000/offers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZpc2gxQGJpZy5sb2NhbCIsImlkIjoiNjM1N2Q0NTFjODQ5NWI5MzhhZjFjODE5IiwiaWF0IjoxNjY2NzAwMzg2LCJleHAiOjE2NjY4NzMxODZ9.FGJ3f0b60gjNDJFsOLYUalMInW8XS23eSWy9-Hp4OzE

{
  "title": "Perfectly located TEST",
  "description": "Odio pellentesque diam",
  "city": {
    "name": "Hamburg",
    "location": {
      "latitude": 53.550341,
      "longitude": 10.000654
    }
  },
  "previewImage": "hotel1.jpg",
  "images": [
    "hotel1.jpg",
    "hotel2.jpg",
    "hotel3.jpg",
    "hotel4.jpg",
    "hotel5.jpg",
    "hotel6.jpg"
  ],
  "isPremium": false,
  "rating": 4,
  "type": "Apartment",
  "bedrooms": 3,
  "maxAdults": 2,
  "price": 13929,
  "goods": [
    "Fridge",
    "LaptopFriendlyWorkspace",
    "Towels",
    "Washer"
  ],
  "host": "63358c4010021a05e36db0bf",
  "location": {
    "latitude": 53.550341,
    "longitude": 10.000654
  }
}

###
## delete offer
DELETE http://localhost:9000/offers/634527199c42583bf5b1f0a1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZpc2gxQGJpZy5sb2NhbCIsImlkIjoiNjM1N2Q0NTFjODQ5NWI5MzhhZjFjODE5IiwiaWF0IjoxNjY2NzAwMzg2LCJleHAiOjE2NjY4NzMxODZ9.FGJ3f0b60gjNDJFsOLYUalMInW8XS23eSWy9-Hp4OzE

###
## update offer
PATCH http://localhost:9000/offers/634527199c42583bf5b1f0a4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZpc2gxQGJpZy5sb2NhbCIsImlkIjoiNjM1N2Q0NTFjODQ5NWI5MzhhZjFjODE5IiwiaWF0IjoxNjY2NzAwMzg2LCJleHAiOjE2NjY4NzMxODZ9.FGJ3f0b60gjNDJFsOLYUalMInW8XS23eSWy9-Hp4OzE

 {
   "title": "test2",
   "description": "test2",
   "price": 2200
 }

###
## get comments offer
 GET http://localhost:9000/offers/634527199c42583bf5b1f0a4/comments HTTP/1.1

###
## create comment
POST http://localhost:9000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZpc2gxQGJpZy5sb2NhbCIsImlkIjoiNjM1N2Q0NTFjODQ5NWI5MzhhZjFjODE5IiwiaWF0IjoxNjY2NzAwMzg2LCJleHAiOjE2NjY4NzMxODZ9.FGJ3f0b60gjNDJFsOLYUalMInW8XS23eSWy9-Hp4OzE

 {
   "text": "perfect location",
   "offerId": "634527199c42583bf5b1f0a4",
   "rating": 4
 }

### users
### register user
POST http://localhost:9000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "fish@big.local",
  "name": "Sophie",
  "password": "1234567890",
  "typeUser": "Normal"
}

### login user
POST http://localhost:9000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "fish1@big.local",
  "password": "1234567890"
}

### load user avatar
POST http://localhost:9000/users/63358c4010021a05e36db0bf/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/jpeg

< ../markup/img/avatar-angelina.jpg
--WebAppBoundary--

### check token
GET http://localhost:9000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZpc2gxQGJpZy5sb2NhbCIsImlkIjoiNjM1N2Q0NTFjODQ5NWI5MzhhZjFjODE5IiwiaWF0IjoxNjY2NzAwMzg2LCJleHAiOjE2NjY4NzMxODZ9.FGJ3f0b60gjNDJFsOLYUalMInW8XS23eSWy9-Hp4OzE
