###
#offers
##get offers
GET http://localhost:9000/offers HTTP/1.1

###
##get offer by Id
GET http://localhost:9000/offers/634527199c42583bf5b1f0a4 HTTP/1.1

###
## create offer
POST http://localhost:9000/offers/ HTTP/1.1
Content-Type: application/json

{
  "title": "Perfectly located TEST",
  "description": "Odio pellentesque diam",
  "city": {
    "name": "Hamburg",
    "location": {
      "latitude": 53.550341,
      "longitude": 10.000654
    }
  },
  "previewImage": "hotel1.jpg",
  "images": [
    "hotel1.jpg",
    "hotel2.jpg",
    "hotel3.jpg",
    "hotel4.jpg",
    "hotel5.jpg",
    "hotel6.jpg"
  ],
  "isPremium": false,
  "rating": 4,
  "type": "Apartment",
  "bedrooms": 3,
  "maxAdults": 2,
  "price": 13929,
  "goods": [
    "Fridge",
    "LaptopFriendlyWorkspace",
    "Towels",
    "Washer"
  ],
  "host": "63358c4010021a05e36db0bf",
  "location": {
    "latitude": 53.550341,
    "longitude": 10.000654
  }
}

###
## delete offer

 DELETE http://localhost:9000/offers/634527199c42583bf5b1f0a1 HTTP/1.1

###
## update offer

 PATCH http://localhost:9000/offers/634527199c42583bf5b1f0a4 HTTP/1.1
 Content-Type: application/json

 {
   "title": "test1",
   "description": "test1",
   "price": 2200
 }

###
## get comments offer

 GET http://localhost:9000/offers/634527199c42583bf5b1f0a/comments HTTP/1.1

###
## create comment
 POST http://localhost:9000/comments HTTP/1.1
 Content-Type: application/json

 {
   "text": "perfect location",
   "offerId": "634527199c42583bf5b1f0a7",
   "userId": "63358c4010021a05e36db0bf",
   "rating": 4
 }

### users
POST http://localhost:9000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "fish@big.local",
  "avatarUrl": "awesome-avatar.jpg",
  "name": "Sophie",
  "userType": "Normal",
  "password": "1234567890"
}

### load user avatar
POST http://localhost:9000/users/63358c4010021a05e36db0bf/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/jpeg

< ../markup/img/avatar-angelina.jpg
--WebAppBoundary--
